# Generated by Django 5.1.2 on 2024-10-31 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 11, 19, 27, 957914, tzinfo=datetime.timezone.utc)),
        ),
    ]
