# Generated by Django 5.1 on 2024-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0002_client_product_blocked_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='shop_avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
