# Generated by Django 5.1 on 2024-10-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0002_remove_product_gray_price_client_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='shop_address',
        ),
    ]
