# Generated by Django 5.1 on 2024-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0003_alter_client_shop_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_key',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
