# Generated by Django 5.1 on 2024-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0003_remove_client_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
