# Generated by Django 5.1 on 2024-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0004_client_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gray_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='it',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
