# Generated by Django 5.1 on 2024-09-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0004_client_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gray_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
