# Generated by Django 5.1 on 2024-10-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0004_alter_client_shop_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_product',
            field=models.IntegerField(default=-1),
        ),
    ]
