# Generated by Django 5.1 on 2024-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0005_product_gray_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'offer_id')},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop', 'offer_id'), name='unique_shop_offer'),
        ),
    ]
