# Generated by Django 5.1 on 2024-09-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0008_product_it'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_shop_offer',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
